Repository schalkneethling/developer-toolchest, pull requests merged in 2022-06, with the labels that each got.

#145 Adds 3 tools and corrects typo
  src/data/tools.json
Labels: community

#147 Add evernote.design tool
  src/data/tools.json
Labels: enhancement, community

#149 chore: add tools
  src/data/tools.json
Labels: enhancement, chore

#150 Update tools.json
  src/data/tools.json
Labels: enhancement, chore
