Repository schalkneethling/developer-toolchest, pull requests merged in 2022-10, with the labels that each got.

#197 Added NVM
  src/data/tools.json
Labels: hacktoberfest, hacktoberfest-accepted

#199 feat: add gradient generator by josh comeau
  src/data/tools.json
Labels: hacktoberfest, hacktoberfest-accepted

#202 added tools, added image
  public/logos/Pexels.png
  src/data/tools.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#203 Regexp
  src/data/tools.json
Labels: chore

#206 bug: add target-repo
  .github/workflows/auto-merge.yml
Labels: bug

#209 chore: Add Mozilla observatory
  public/logos/mozilla-observatory.png
  src/data/tools.json
Labels: chore

#198 Add JSON Diff and ModHeader
  public/logos/modheader.png
  src/data/tools.json
Labels: enhancement, community, hacktoberfest, hacktoberfest-accepted

#207 185 adding qrcodemonkey
  public/logos/Pngegg.png
  public/logos/qrcodemonkey.png
  src/data/tools.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#216 fix: add lazy loading to logo image
  src/ui/molecules/card/index.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#217 chore: Add Vite
  public/logos/vite-logo.png
  src/data/tools.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#218 chore: add jitsu
  public/index.html
Labels: chore
